site_name: PembrokePSui
repo_url: https://github.com/jpsider/PembrokePSui
theme: readthedocs
pages:
- Home: index.md
- PembrokePSui Basics:
  - What is PembrokePSui: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Basic Commands:
- Examples:
- Acknowledgements: acknowledgements.md
